plugins {
    id("java")
    id("io.qameta.allure") version "2.12.0"
}

group = "ru.netology"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    gradlePluginPortal()
}

allure {
    version = "2.27.0"
    adapter {
        frameworks {
            junit5 {
                enabled.set(true)
            }
        }
    }
}

dependencies {
    // --- JUnit 5 ---
    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    // --- Selenium + Appium ---
    implementation("org.seleniumhq.selenium:selenium-java:4.25.0")
    implementation("io.appium:java-client:9.2.2")

    // --- Allure ---
    testImplementation("io.qameta.allure:allure-selenide:2.27.0")
}

tasks.test {
    useJUnitPlatform()
}